import { checkCookies, getCookie, getCookies } from "cookies-next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import axios from "axios";
import { useEffect,useState } from "react";
export default function Home() {

  const [text,setText] = useState("");

  useEffect(() => {

    const res  = axios.get("/api/hello").then(res => {
      console.log(res.data);
      setText(res.data.message);
    })
  }, []);



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/api/google">Login with Google</Link>
    </div>
  );
}

export async function getServerSideProps({ req, res }) {
  try {
    const cookieExists = getCookie("token", { req, res });
    console.log(cookieExists);
    if (cookieExists) return { redirect: { destination: "/dashboard" } };
    return { props: {} };
  } catch (err) {
    return { props: {} };
  }
}
